import { CampusItem } from './types.ts';

export const INITIAL_CAMPUS_ITEMS: CampusItem[] = [
  {
    id: 'item-lost-1',
    type: 'lost',
    title: 'Silver MacBook Air M2 13-inch',
    category: 'Electronics',
    description: 'Silver 13" MacBook Air with a teal protective hardshell case. Has a GitHub octocat sticker and a National Parks sticker on the lid. Left on a desk next to the window.',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    location: 'Main Library - 2nd Floor Silent Study Area',
    dateTime: '2026-09-14T15:30',
    contactName: 'Elena Rostova',
    contactEmail: 'elena.rostova@campus.edu',
    contactPhone: '(555) 234-8901',
    status: 'open',
    createdAt: '2026-09-14T16:00:00.000Z',
  },
  {
    id: 'item-found-1',
    type: 'found',
    title: 'Apple MacBook Laptop with Stickers',
    category: 'Electronics',
    description: 'Found a silver Apple laptop inside a blue/teal clip-on case. Noticed multiple vinyl decals including an octocat and outdoor landscape decal on the outside. Turned in by custodian.',
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    location: 'Main Library 2nd floor desk area',
    dateTime: '2026-09-14T18:00',
    contactName: 'Library Circulation Desk (Officer Miller)',
    contactEmail: 'library-lostfound@campus.edu',
    contactPhone: '(555) 901-4433',
    storageLocation: 'Library Circulation Desk - Secured Locker #4',
    status: 'open',
    createdAt: '2026-09-14T18:15:00.000Z',
  },
  {
    id: 'item-lost-2',
    type: 'lost',
    title: 'AirPods Pro with Matte Neon Green Case',
    category: 'Electronics',
    description: 'AirPods Pro 2nd Gen inside an eye-catching neon/lime green silicone case with a black carabiner clip. Lost during evening basketball practice.',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    location: 'North Recreation Center - Basketball Court 2',
    dateTime: '2026-09-13T19:00',
    contactName: 'Jordan Kim',
    contactEmail: 'jkim24@campus.edu',
    contactPhone: '(555) 782-9912',
    status: 'open',
    createdAt: '2026-09-13T20:30:00.000Z',
  },
  {
    id: 'item-found-2',
    type: 'found',
    title: 'Wireless Earbuds in Bright Green Silicone Sleeve',
    category: 'Electronics',
    description: 'White Apple earbuds charging case enclosed in a bright lime silicone sleeve with a small black clip attached. Picked up on bleachers near gym court.',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    location: 'North Gym Bleachers',
    dateTime: '2026-09-13T21:15',
    contactName: 'Coach Henderson / Gym Staff',
    contactEmail: 'rec-services@campus.edu',
    contactPhone: '(555) 782-0100',
    storageLocation: 'Gym Front Desk Lost & Found Bin',
    status: 'open',
    createdAt: '2026-09-13T21:40:00.000Z',
  },
  {
    id: 'item-lost-3',
    type: 'lost',
    title: 'Campus Student ID Card - Marcus Vance',
    category: 'IDs & Cards',
    description: 'Official University ID card belonging to Marcus Vance, Sophomore ID #904821. In a clear plastic sleeve with a red campus lanyard and dorm swipe key.',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    location: 'Student Dining Commons or walkway toward Science Hall',
    dateTime: '2026-09-15T09:15',
    contactName: 'Marcus Vance',
    contactEmail: 'mvance@campus.edu',
    contactPhone: '(555) 345-6712',
    status: 'open',
    createdAt: '2026-09-15T09:45:00.000Z',
  },
  {
    id: 'item-found-3',
    type: 'found',
    title: 'University Lanyard with Student Card & Key',
    category: 'IDs & Cards',
    description: 'Crimson campus branded lanyard with student photo identification card (first name Marcus) and blue electronic dorm fob.',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80',
    location: 'Pathway outside Chemistry Annex',
    dateTime: '2026-09-15T10:00',
    contactName: 'Campus Public Safety Office',
    contactEmail: 'publicsafety@campus.edu',
    contactPhone: '(555) 911-0000',
    storageLocation: 'Public Safety HQ - Desk A',
    status: 'open',
    createdAt: '2026-09-15T10:15:00.000Z',
  },
  {
    id: 'item-lost-4',
    type: 'lost',
    title: 'Navy Blue Fjallraven Kanken Backpack',
    category: 'Wallets & Bags',
    description: 'Dark blue backpack containing Organic Chemistry lecture binder, Texas Instruments TI-84 calculator, and a yellow pencil case.',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    location: 'Science Auditorium 101, row F',
    dateTime: '2026-09-12T14:00',
    contactName: 'Sarah Jenkins',
    contactEmail: 's.jenkins@campus.edu',
    contactPhone: '(555) 602-1144',
    status: 'open',
    createdAt: '2026-09-12T15:10:00.000Z',
  },
  {
    id: 'item-found-4',
    type: 'found',
    title: 'Hydro Flask 32oz Wide Mouth in Pacific Blue',
    category: 'Water Bottles & Tumblers',
    description: 'Pacific blue 32oz insulated metal flask. Has scratches around the bottom rim and a sticker that says "Code. Eat. Sleep."',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    location: 'Engineering Building Lab 304',
    dateTime: '2026-09-14T11:20',
    contactName: 'Lab TA Priya',
    contactEmail: 'priya.ta@campus.edu',
    contactPhone: '(555) 431-8890',
    storageLocation: 'Lab 304 Teaching Assistant Office',
    status: 'open',
    createdAt: '2026-09-14T11:45:00.000Z',
  },
];
